insert into product (id, name, brand, made_in, price) values (1, 'Burger Veggie', 'Oil-Free Acne Wash', 'Guyana', 113802);
insert into product (id, name, brand, made_in, price) values (2, 'Nori Sea Weed - Gold Label', 'SELENIUM SULFIDE', 'Peru', 469135);
insert into product (id, name, brand, made_in, price) values (3, 'Bread - Pullman, Sliced', 'Amber Amethyst Teething Relief', 'Indonesia', 473759);
insert into product (id, name, brand, made_in, price) values (4, 'Chips - Potato Jalapeno', 'Alpan 40 (Number 110)', 'Bulgaria', 148119);
insert into product (id, name, brand, made_in, price) values (5, 'Squid Ink', 'Nicotine Polacrilex, Coated Fruit Flavor', 'China', 226766);
insert into product (id, name, brand, made_in, price) values (6, 'Tuna - Bluefin', 'OsmoPrep', 'China', 322742);
insert into product (id, name, brand, made_in, price) values (7, 'Wine - Acient Coast Caberne', 'OPANA', 'Portugal', 152578);
insert into product (id, name, brand, made_in, price) values (8, 'Milk - Condensed', 'PHENADOZ', 'Thailand', 125681);
insert into product (id, name, brand, made_in, price) values (9, 'Nantucket - 518ml', 'Lisinopril', 'Poland', 357014);
insert into product (id, name, brand, made_in, price) values (10, 'Pears - Bosc', 'Standardized Bermuda Grass Pollen', 'Georgia', 37149);
insert into product (id, name, brand, made_in, price) values (11, 'Coffee - French Vanilla Frothy', 'Loratadine and Pseudoephedrine Sulfate', 'Brazil', 97252);
insert into product (id, name, brand, made_in, price) values (12, 'Lettuce - Lolla Rosa', 'Ibuprofen', 'Portugal', 41220);
insert into product (id, name, brand, made_in, price) values (13, 'Beer - Moosehead', 'Dandruff', 'Russia', 254571);
insert into product (id, name, brand, made_in, price) values (14, 'Trout - Hot Smkd, Dbl Fillet', 'health mart daytime', 'Indonesia', 284947);
insert into product (id, name, brand, made_in, price) values (15, 'Oil - Shortening,liqud, Fry', 'pravastatin sodium', 'China', 353978);
insert into product (id, name, brand, made_in, price) values (16, 'Horseradish - Prepared', 'Tobramycin', 'Greenland', 417804);
insert into product (id, name, brand, made_in, price) values (17, 'Beer - Tetleys', 'Brain Balance', 'Indonesia', 347759);
insert into product (id, name, brand, made_in, price) values (18, 'Cup - 4oz Translucent', 'Pollens - Weeds, Weed mix 2630', 'Pakistan', 460504);
insert into product (id, name, brand, made_in, price) values (19, 'Salad Dressing', 'PrandiMet', 'France', 146078);
insert into product (id, name, brand, made_in, price) values (20, 'Lemonade - Black Cherry, 591 Ml', 'Pulsatilla Tormentilla', 'Nigeria', 286786);
insert into product (id, name, brand, made_in, price) values (21, 'Dome Lid Clear P92008h', 'ADVANCED MARINE BIOLOGY DAY SUNSCREEN BROAD SPECTRUM SPF 20', 'Nigeria', 434268);
insert into product (id, name, brand, made_in, price) values (22, 'Dragon Fruit', 'Health Smart Instant Hand Sanitizer with aloe vera and vitamin e sweet pea', 'China', 122417);
insert into product (id, name, brand, made_in, price) values (23, 'Tart Shells - Sweet, 4', 'Pioglitazone', 'Philippines', 204045);
insert into product (id, name, brand, made_in, price) values (24, 'Soup - Chicken And Wild Rice', 'good sense night time', 'Indonesia', 128719);
insert into product (id, name, brand, made_in, price) values (25, 'Beer - Corona', 'Alcohol', 'Colombia', 54941);
insert into product (id, name, brand, made_in, price) values (26, 'Milk - Chocolate 500ml', 'Zep Foam San', 'Norway', 145362);
insert into product (id, name, brand, made_in, price) values (27, 'Pear - Halves', 'Sodium Chloride', 'China', 379642);
insert into product (id, name, brand, made_in, price) values (28, 'Chicken - Ground', 'Penicillin V Potassium', 'China', 349649);
insert into product (id, name, brand, made_in, price) values (29, 'Dragon Fruit', 'NITROUS OXIDE', 'Indonesia', 480669);
insert into product (id, name, brand, made_in, price) values (30, 'Pea - Snow', 'Cefuroxime Axetil', 'China', 409365);
insert into product (id, name, brand, made_in, price) values (31, 'Cattail Hearts', 'Olay Complete All Day', 'Philippines', 420855);
insert into product (id, name, brand, made_in, price) values (32, 'Potatoes - Parissienne', 'Silicea Kit Refill', 'China', 231683);
insert into product (id, name, brand, made_in, price) values (33, 'Edible Flower - Mixed', 'Live Better', 'China', 336765);
insert into product (id, name, brand, made_in, price) values (34, 'Wine - Rioja Campo Viejo', 'Vermex', 'Russia', 253172);
insert into product (id, name, brand, made_in, price) values (35, 'Pastry - Trippleberry Muffin - Mini', 'Listerine Essential Care', 'China', 258308);
insert into product (id, name, brand, made_in, price) values (36, 'Cheese Cloth', 'Bupropion Hydrochloride', 'Kuwait', 203571);
insert into product (id, name, brand, made_in, price) values (37, 'Wine - Pinot Noir Pond Haddock', 'Goodys Headache Relief Shot', 'Indonesia', 327828);
insert into product (id, name, brand, made_in, price) values (38, 'Oil - Grapeseed Oil', 'Ibuprofen', 'Croatia', 469442);
insert into product (id, name, brand, made_in, price) values (39, 'Grapes - Red', 'Diclofenac Sodium', 'Germany', 234401);
insert into product (id, name, brand, made_in, price) values (40, 'Brandy - Orange, Mc Guiness', 'ECLIPSE SPF 50', 'Malawi', 88903);
insert into product (id, name, brand, made_in, price) values (41, 'Pie Shell - 5', 'Oxygen', 'Indonesia', 174413);
insert into product (id, name, brand, made_in, price) values (42, 'Oven Mitt - 13 Inch', 'Extra Strength Pain Relief', 'Russia', 181255);
insert into product (id, name, brand, made_in, price) values (43, 'Bag - Bread, White, Plain', 'DIORSNOW UV SHIELD BB CREME WHITE REVEAL UV PROTECTION SPF 50', 'China', 158741);
insert into product (id, name, brand, made_in, price) values (44, 'Tomato - Green', 'Ocean Potion Instant Dry 30 Mist Water Sport Sunscreen', 'China', 419197);
insert into product (id, name, brand, made_in, price) values (45, 'V8 Pet', 'Tobacco Leaf', 'Russia', 465860);
insert into product (id, name, brand, made_in, price) values (46, 'Marzipan 50/50', 'Fexmid', 'Armenia', 103291);
insert into product (id, name, brand, made_in, price) values (47, 'Sage - Fresh', 'donepezil hydrochloride', 'Poland', 166751);
insert into product (id, name, brand, made_in, price) values (48, 'Sunflower Seed Raw', 'Sweet Gum', 'Indonesia', 394975);
insert into product (id, name, brand, made_in, price) values (49, 'Cookies - Englishbay Wht', 'Agropharma Isopropyl Alcohol', 'Hungary', 435886);
insert into product (id, name, brand, made_in, price) values (50, 'Paper - Brown Paper Mini Cups', 'Tension Headache Relief', 'Portugal', 494288);