insert into people (full_name, job, gender, city, salary) values ('Emylee', 'Physical Therapy Assistant', 'Genderfluid', 'Rossosh’', 2235);
insert into people (full_name, job, gender, city, salary) values ('Shannan', 'Human Resources Manager', 'Male', 'Dinājpur', 1407);
insert into people (full_name, job, gender, city, salary) values ('Abbott', 'Information Systems Manager', 'Male', 'Margoyoso', 430);
insert into people (full_name, job, gender, city, salary) values ('Dell', 'Desktop Support Technician', 'Non-binary', 'Pangtangis Dajah', 2606);
insert into people (full_name, job, gender, city, salary) values ('Georgie', 'Paralegal', 'Non-binary', 'Taiqing', 1619);
insert into people (full_name, job, gender, city, salary) values ('Merissa', 'Systems Administrator IV', 'Male', 'Basco', 1789);
insert into people (full_name, job, gender, city, salary) values ('Dulcine', 'Quality Engineer', 'Male', 'Nikol’sk', 603);
insert into people (full_name, job, gender, city, salary) values ('Corliss', 'Nurse Practicioner', 'Agender', 'Casal das Figueiras', 2985);
insert into people (full_name, job, gender, city, salary) values ('Carleen', 'Computer Systems Analyst IV', 'Polygender', 'Emiliano Zapata', 685);
insert into people (full_name, job, gender, city, salary) values ('Valaria', 'Safety Technician IV', 'Polygender', 'Ropice', 2598);
insert into people (full_name, job, gender, city, salary) values ('Andromache', 'Design Engineer', 'Polygender', 'Bayanhongor', 859);
insert into people (full_name, job, gender, city, salary) values ('Eugine', 'VP Product Management', 'Bigender', 'Ambon', 447);
insert into people (full_name, job, gender, city, salary) values ('Tessy', 'Budget/Accounting Analyst IV', 'Genderqueer', 'Miracema', 2970);
insert into people (full_name, job, gender, city, salary) values ('Luz', 'Research Assistant IV', 'Genderfluid', 'Leticia', 2740);
insert into people (full_name, job, gender, city, salary) values ('Cleopatra', 'Occupational Therapist', 'Genderqueer', 'Buena Esperanza', 827);
insert into people (full_name, job, gender, city, salary) values ('Natalee', 'Executive Secretary', 'Polygender', 'Mulatupo', 2893);
insert into people (full_name, job, gender, city, salary) values ('Frasier', 'VP Marketing', 'Genderqueer', 'Gangjia', 831);
insert into people (full_name, job, gender, city, salary) values ('Ike', 'Recruiter', 'Polygender', 'Xidianzi', 1629);
insert into people (full_name, job, gender, city, salary) values ('Janice', 'Registered Nurse', 'Male', 'Seka', 2905);
insert into people (full_name, job, gender, city, salary) values ('Gayleen', 'Research Associate', 'Polygender', 'Changliu', 456);
insert into people (full_name, job, gender, city, salary) values ('Trent', 'Project Manager', 'Genderfluid', 'Novopodrezkovo', 2928);
insert into people (full_name, job, gender, city, salary) values ('Cristiano', 'Nurse', 'Female', 'Laslovo', 921);
insert into people (full_name, job, gender, city, salary) values ('Patrice', 'Database Administrator IV', 'Genderfluid', 'Xiaogang', 807);
insert into people (full_name, job, gender, city, salary) values ('Darleen', 'Nurse', 'Genderfluid', 'San José', 2506);
insert into people (full_name, job, gender, city, salary) values ('Palm', 'Accountant I', 'Non-binary', 'Miyako', 2389);
insert into people (full_name, job, gender, city, salary) values ('Grannie', 'Chemical Engineer', 'Genderfluid', 'Górki Wielkie', 2159);
insert into people (full_name, job, gender, city, salary) values ('Lyndsie', 'Staff Scientist', 'Agender', 'Akunk’', 2161);
insert into people (full_name, job, gender, city, salary) values ('Eveleen', 'Junior Executive', 'Female', 'Lukrejo', 2094);
insert into people (full_name, job, gender, city, salary) values ('Kenon', 'Tax Accountant', 'Female', 'Pasaje', 2336);
insert into people (full_name, job, gender, city, salary) values ('Dayna', 'Desktop Support Technician', 'Female', 'Kompaniyivka', 654);
insert into people (full_name, job, gender, city, salary) values ('Quentin', 'Database Administrator IV', 'Bigender', 'Javānrūd', 936);
insert into people (full_name, job, gender, city, salary) values ('Horton', 'Safety Technician II', 'Male', 'Paterson', 462);
insert into people (full_name, job, gender, city, salary) values ('Annice', 'Nurse Practicioner', 'Genderqueer', 'Velký Týnec', 2223);
insert into people (full_name, job, gender, city, salary) values ('Corliss', 'Analyst Programmer', 'Agender', 'Guazapa', 1468);
insert into people (full_name, job, gender, city, salary) values ('Katusha', 'Assistant Professor', 'Polygender', 'Melekyne', 1171);
insert into people (full_name, job, gender, city, salary) values ('Kienan', 'Database Administrator II', 'Genderfluid', 'Askim', 2201);
insert into people (full_name, job, gender, city, salary) values ('Stephani', 'Assistant Media Planner', 'Bigender', 'Changxing', 1680);
insert into people (full_name, job, gender, city, salary) values ('Chen', 'Legal Assistant', 'Bigender', 'Raheny', 1784);
insert into people (full_name, job, gender, city, salary) values ('Ingram', 'Administrative Officer', 'Genderqueer', 'Kadubadak', 2747);
insert into people (full_name, job, gender, city, salary) values ('Cherida', 'Teacher', 'Bigender', 'Tangxi', 2187);
insert into people (full_name, job, gender, city, salary) values ('Brennan', 'Structural Analysis Engineer', 'Non-binary', 'Pinaring', 2362);
insert into people (full_name, job, gender, city, salary) values ('Veronike', 'General Manager', 'Genderfluid', 'Sungaibengkal', 2539);
insert into people (full_name, job, gender, city, salary) values ('Dodie', 'GIS Technical Architect', 'Polygender', 'Ramenki', 2485);
insert into people (full_name, job, gender, city, salary) values ('Clarinda', 'Marketing Manager', 'Non-binary', 'Cibunar', 1100);
insert into people (full_name, job, gender, city, salary) values ('Shela', 'Account Representative II', 'Polygender', 'Kvänum', 727);
insert into people (full_name, job, gender, city, salary) values ('Vale', 'General Manager', 'Female', 'Batan', 518);
insert into people (full_name, job, gender, city, salary) values ('Petronilla', 'Senior Quality Engineer', 'Female', 'Teplice', 2865);
insert into people (full_name, job, gender, city, salary) values ('Roger', 'Analog Circuit Design manager', 'Genderfluid', 'Pulau Tiga', 425);
insert into people (full_name, job, gender, city, salary) values ('Lenci', 'Accountant III', 'Agender', 'Aksha', 1885);
insert into people (full_name, job, gender, city, salary) values ('Cori', 'Design Engineer', 'Female', 'San Francisco', 650);
insert into people (full_name, job, gender, city, salary) values ('Christie', 'Statistician I', 'Bigender', 'Luau', 2498);
insert into people (full_name, job, gender, city, salary) values ('Margot', 'Developer IV', 'Genderqueer', 'Kayan', 2389);
insert into people (full_name, job, gender, city, salary) values ('Janka', 'Occupational Therapist', 'Male', 'Doba', 2147);
insert into people (full_name, job, gender, city, salary) values ('Sherlock', 'Accountant I', 'Genderqueer', 'Jiangpu', 2969);
insert into people (full_name, job, gender, city, salary) values ('Joy', 'VP Quality Control', 'Female', 'Tucson', 2551);
insert into people (full_name, job, gender, city, salary) values ('Jacobo', 'Chief Design Engineer', 'Genderfluid', 'Shuanglongchang', 773);
insert into people (full_name, job, gender, city, salary) values ('Sully', 'Analog Circuit Design manager', 'Male', 'Sumberagung', 429);
insert into people (full_name, job, gender, city, salary) values ('Birgit', 'Graphic Designer', 'Genderqueer', 'Pofadder', 1925);
insert into people (full_name, job, gender, city, salary) values ('Derk', 'Internal Auditor', 'Polygender', 'Manhuaçu', 1189);
insert into people (full_name, job, gender, city, salary) values ('Cobb', 'Physical Therapy Assistant', 'Male', 'Orion', 1420);
insert into people (full_name, job, gender, city, salary) values ('Valry', 'Payment Adjustment Coordinator', 'Agender', 'Tangquan', 2593);
insert into people (full_name, job, gender, city, salary) values ('Pietra', 'Senior Developer', 'Agender', 'Daxi', 2042);
insert into people (full_name, job, gender, city, salary) values ('Saxe', 'Actuary', 'Female', 'Qiryat Shemona', 2397);
insert into people (full_name, job, gender, city, salary) values ('Cissy', 'Clinical Specialist', 'Male', 'Padas', 1575);
insert into people (full_name, job, gender, city, salary) values ('Conway', 'Tax Accountant', 'Genderqueer', 'Tulusmulyo', 2551);
insert into people (full_name, job, gender, city, salary) values ('Vina', 'Mechanical Systems Engineer', 'Polygender', 'Tongda', 1891);
insert into people (full_name, job, gender, city, salary) values ('Harriette', 'Tax Accountant', 'Polygender', 'Alagoinhas', 1770);
insert into people (full_name, job, gender, city, salary) values ('Dorelle', 'Research Nurse', 'Non-binary', 'Dahe', 1007);
insert into people (full_name, job, gender, city, salary) values ('Dal', 'Tax Accountant', 'Genderfluid', 'Xiangzikou', 1490);
insert into people (full_name, job, gender, city, salary) values ('Rosalyn', 'Account Representative III', 'Male', 'Zhongguanyi', 2124);
insert into people (full_name, job, gender, city, salary) values ('Esmaria', 'Nurse', 'Bigender', 'Kabor', 2784);
insert into people (full_name, job, gender, city, salary) values ('Jodee', 'Computer Systems Analyst III', 'Genderfluid', 'Pukou', 2258);
insert into people (full_name, job, gender, city, salary) values ('Laraine', 'Quality Control Specialist', 'Non-binary', 'Hamburg Bramfeld', 2897);
insert into people (full_name, job, gender, city, salary) values ('Shay', 'Human Resources Manager', 'Polygender', 'Fenais da Ajuda', 1686);
insert into people (full_name, job, gender, city, salary) values ('Junia', 'VP Quality Control', 'Agender', 'Porto Alto', 2476);
insert into people (full_name, job, gender, city, salary) values ('Cassaundra', 'Actuary', 'Polygender', 'Criação Velha', 568);
insert into people (full_name, job, gender, city, salary) values ('Jamal', 'Director of Sales', 'Genderfluid', 'Mintian', 962);
insert into people (full_name, job, gender, city, salary) values ('Shermie', 'Chief Design Engineer', 'Male', 'Buenavista', 666);
insert into people (full_name, job, gender, city, salary) values ('Horst', 'Marketing Manager', 'Polygender', 'Thành Phố Hà Giang', 2506);
insert into people (full_name, job, gender, city, salary) values ('Jenda', 'Structural Analysis Engineer', 'Genderqueer', 'Hamm', 408);
insert into people (full_name, job, gender, city, salary) values ('Ines', 'Business Systems Development Analyst', 'Agender', 'Těšany', 1135);
insert into people (full_name, job, gender, city, salary) values ('Prinz', 'Nurse Practicioner', 'Non-binary', 'Margoyoso', 1498);
insert into people (full_name, job, gender, city, salary) values ('Kimberli', 'Web Developer I', 'Female', 'Daying', 2793);
insert into people (full_name, job, gender, city, salary) values ('Frederik', 'Marketing Assistant', 'Female', 'Bunobogu', 2387);
insert into people (full_name, job, gender, city, salary) values ('Barbey', 'Biostatistician II', 'Male', 'Washington', 1635);
insert into people (full_name, job, gender, city, salary) values ('Frank', 'Human Resources Assistant I', 'Male', 'Staraya Ladoga', 2698);
insert into people (full_name, job, gender, city, salary) values ('Isahella', 'Staff Scientist', 'Male', 'Oemofa', 2156);
insert into people (full_name, job, gender, city, salary) values ('Kati', 'Assistant Manager', 'Polygender', 'Anshan', 575);
insert into people (full_name, job, gender, city, salary) values ('Alfie', 'Safety Technician II', 'Genderqueer', 'Napuro', 2039);
insert into people (full_name, job, gender, city, salary) values ('Odelinda', 'Senior Financial Analyst', 'Bigender', 'Liaobu', 2089);
insert into people (full_name, job, gender, city, salary) values ('Prisca', 'Accountant III', 'Polygender', 'Cobre', 2649);
insert into people (full_name, job, gender, city, salary) values ('Brittany', 'Software Consultant', 'Male', 'Xushuguan', 1466);
insert into people (full_name, job, gender, city, salary) values ('Evy', 'Teacher', 'Non-binary', 'Jiuzhou', 2896);
insert into people (full_name, job, gender, city, salary) values ('Jackelyn', 'Senior Editor', 'Non-binary', 'Zhavoronki', 1884);
insert into people (full_name, job, gender, city, salary) values ('Maryanna', 'Associate Professor', 'Female', 'Dapuchaihe', 2392);
insert into people (full_name, job, gender, city, salary) values ('Roi', 'VP Quality Control', 'Polygender', 'Tiko', 2600);
insert into people (full_name, job, gender, city, salary) values ('Hanny', 'Geologist IV', 'Female', 'Sukmoilang', 2012);
insert into people (full_name, job, gender, city, salary) values ('Bobine', 'Research Associate', 'Genderfluid', 'Tandou', 2644);
insert into people (full_name, job, gender, city, salary) values ('Carol-jean', 'Web Developer II', 'Polygender', 'Ḩammām Damt', 1956);
insert into people (full_name, job, gender, city, salary) values ('Pearl', 'VP Marketing', 'Non-binary', 'San Juan', 914);