DROP TABLE IF EXISTS TBL_CUSTOMERS;
 
CREATE TABLE TBL_CUSTOMERS (
  id BIGINT IDENTITY(1,1) PRIMARY KEY ,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(100) DEFAULT NULL,
  mobile VARCHAR(50) DEFAULT NULL,
  job VARCHAR(100) DEFAULT NULL
);

